#line 1 "lexicon.cpp"

#line 3 "lexicon.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[412] =
    {   0,
        0,    0,  100,   98,   37,   37,   96,   98,   98,   78,
       79,   87,   89,   82,   77,   97,   88,   73,   73,   83,
       93,   76,   95,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   86,   75,   75,   80,   98,   81,   37,   91,    0,
       84,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   74,    0,
       73,   73,   92,   90,   94,   75,   75,   75,   75,   75,
       65,   75,   75,   75,   75,   75,   75,   75,   75,   59,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,

       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   85,    2,    0,    0,    0,    0,   16,
        0,    0,    0,    0,    0,    0,   19,    0,    0,    0,
       20,    0,   21,    0,    0,    0,    0,    0,   17,    0,
       18,    0,    0,    0,    1,   74,   75,   75,   75,   75,
       75,   75,   47,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   39,   75,   75,   38,   75,   69,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,    0,    5,    0,    0,    0,    6,    0,
        7,    0,    8,    0,    9,    0,   10,    0,    0,    0,

        0,    0,    0,   75,    4,   57,   75,   40,   75,   75,
       61,   75,   75,   75,   75,   72,   75,   70,   67,   75,
       75,   75,   75,   75,   49,   75,   75,   75,   53,   60,
        3,   51,   58,   75,   75,   75,   75,   75,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   56,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   64,   75,   75,   36,    0,
        0,    0,    0,    0,    0,   11,    0,   12,    0,   13,
        0,   14,    0,   15,    0,    0,    0,    0,    0,    0,

        0,   22,    0,    0,   75,   75,   75,   75,   48,   62,
       63,   75,   75,   75,   42,   75,   54,   41,   71,   75,
       50,   75,   75,   75,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   75,   75,   75,
       75,   75,   75,   75,   55,    0,    0,    0,    0,   33,
        0,    0,    0,   34,    0,    0,    0,    0,    0,   32,
        0,   75,   68,   75,   75,   75,   75,   52,    0,    0,
       24,    0,   25,    0,   29,    0,   26,    0,   30,    0,
        0,   35,    0,    0,   28,   75,   66,   75,   75,   43,
        0,    0,   27,    0,   31,   75,   75,    0,   75,   75,

        0,   23,   75,   44,   46,   75,   75,   75,   75,   45,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   22,   22,   23,    1,   24,
       25,   26,    1,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       36,   43,   44,   45,   46,   36,   47,   48,   49,   36,
        1,    1,    1,   50,   51,    1,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   36,   68,   69,   70,   71,   72,   36,   73,
       74,   75,   76,   77,   78,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[79] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[415] =
    {   0,
        0,    0,  656,  657,   77,   79,  630,    0,  648,   81,
      657,  657,  657,  153,  657,  657,   76,   76,   86,  657,
      628,  627,  626,  602,  608,   59,   68,   72,   73,  607,
        0,   81,  612,   75,  580,  579,  599,   91,   69,   84,
       96,  657,  591,  574,  657,  564,  657,   85,  657,  635,
      657,  126,  623,  586,  581,  142,    0,  166,  149,  155,
      580,  579,  568,  577,  157,  163,  127,  629,  214,  225,
      235,  245,  657,  657,  657,    0,  596,  589,   77,  561,
        0,  588,  562,  582,  595,  556,  585,  581,  576,    0,
      575,  581,  577,  552,  544,  545,  572,  568,  572,  547,

      553,  566,  542,  576,  565,  559,  538,  568,  567,   64,
      533,  537,  528,  657,  657,  170,  529,  534,  187,  657,
      190,  198,  266,  268,  270,  272,  657,  542,  522,  274,
      657,  276,  657,  540,  525,  537,  528,  278,  657,  280,
      657,  576,  215,  586,  657,  291,  544,  549,  548,  540,
      530,  556,  516,  550,  529,  513,  534,  550,  535,  544,
      536,  531,  529,  515,  510,  526,  522,    0,  500,   95,
      531,  498,  524,  525,  531,  498,  515,  521,  488,  492,
      493,  486,  498,  312,  657,  497,  525,  314,  657,  316,
      657,  318,  657,  320,  657,  322,  657,  134,  269,  177,

      489,  494,  161,  507,    0,    0,  167,    0,  509,  475,
      511,  291,  477,  513,  498,    0,  509,    0,    0,  485,
      497,  485,  482,  494,    0,  470,  461,  494,  490,    0,
        0,    0,    0,  501,  486,  470,  474,  472,  484,  453,
      452,  456,  471,  325,  328,  330,  332,  346,  449,  453,
      468,  317,  349,  451,  466,  476,  475,  484,  479,  445,
      480,  479,  469,  475,    0,  477,  444,  440,  449,  441,
      463,  449,  432,  467,  433,    0,  438,  432,    0,  440,
      431,  428,  426,  415,  358,  657,  360,  657,  362,  657,
      364,  657,  366,  657,  423,  422,  410,  405,  408,  422,

      370,  657,  412,  401,  426,  425,  436,  419,    0,    0,
        0,  405,  409,  399,    0,  382,    0,    0,    0,  367,
        0,  378,  365,  360,  346,  332,  330,  373,  335,  321,
      375,  329,  326,  324,  300,  377,  297,  310,  304,  304,
      274,  266,  238,  246,    0,  256,  379,  390,  394,  657,
      403,  405,  407,  657,  409,  229,  411,  237,  414,  657,
      418,  245,    0,  261,  220,  222,  169,    0,  148,  420,
      657,  422,  657,  424,  657,  435,  657,  438,  657,  448,
      450,  657,  452,  454,  657,  177,    0,  189,  140,    0,
      142,  456,  657,  459,  657,  124,  134,  462,  121,  108,

      464,  657,  101,  136,    0,   80,   72,   76,   77,    0,
      657,  489,  123,  492
    } ;

static const flex_int16_t yy_def[415] =
    {   0,
      411,    1,  411,  411,  411,  411,  411,  412,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  411,  413,  413,  411,  411,  411,  411,  411,  412,
      411,  411,  411,  411,  411,  411,   14,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  414,  411,  411,
      411,  411,  411,  411,  411,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,

      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  414,  411,  411,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  413,  413,  413,
      413,  413,  413,  413,  413,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  413,  413,  413,  413,  413,  413,  413,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  413,  413,  413,  413,  413,
      411,  411,  411,  411,  411,  413,  413,  411,  413,  413,

      411,  411,  413,  413,  413,  413,  413,  413,  413,  413,
        0,  411,  411,  411
    } ;

static const flex_int16_t yy_nxt[736] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   19,   19,   19,   19,
       19,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   31,   33,   34,   35,   36,
       31,   37,   38,   39,   40,   31,   41,   31,   31,   42,
       31,   31,   31,   31,   31,   31,   43,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   44,
       31,   31,   31,   31,   31,   45,   46,   47,   48,   48,
       48,   48,   52,   52,   67,   79,   48,   48,   69,   68,
       70,   70,   70,   70,   70,   70,   70,   70,   69,   87,

       71,   72,   72,   72,   72,   72,   72,   72,   81,   84,
       88,   85,   90,  102,  149,   93,   82,  104,   80,  150,
       91,   98,  108,  179,  105,   76,  106,   52,   52,  109,
      410,  180,   53,   54,   94,  142,   99,  226,  103,   86,
      409,   83,  100,  119,  119,  408,  101,  110,  407,  107,
      130,  130,   55,   56,   57,   57,  132,  132,  138,  138,
      241,  111,  406,  227,  140,  140,  120,  121,  121,  405,
      143,  184,  184,  131,  242,  243,  404,   53,   54,  133,
      403,  139,  122,  123,  124,  125,  126,  141,  119,  119,
      127,  121,  121,  400,  185,  143,  399,   55,   56,  188,

      188,  254,  255,  249,   58,   59,   60,   61,  257,  258,
      398,  120,  397,   62,  127,  396,   63,  250,  251,  128,
      205,  391,  189,  142,   64,   56,   65,   66,  146,  146,
      146,  146,  146,  146,  146,  146,  129,   69,  390,   70,
       70,   70,   70,   70,   70,   70,   70,   69,  389,   71,
       71,   71,   71,   71,   71,   71,   71,   69,  143,   71,
       72,   72,   72,   72,   72,   72,   72,  190,  190,  192,
      192,  194,  194,  196,  196,  130,  130,  132,  132,  138,
      138,  140,  140,  143,  244,  245,  246,  247,  248,  388,
      191,  387,  193,  386,  195,  383,  197,  380,  131,  369,

      133,  368,  139,  367,  141,  146,  146,  146,  146,  146,
      146,  146,  146,  184,  184,  188,  188,  190,  190,  192,
      192,  194,  194,  196,  196,  262,  285,  285,  263,  287,
      287,  289,  289,  291,  291,  366,  185,  264,  189,  365,
      191,  364,  193,  298,  195,  363,  197,  293,  293,  286,
      301,  301,  288,  362,  290,  361,  292,  299,  300,  285,
      285,  287,  287,  289,  289,  291,  291,  293,  293,  358,
      294,  301,  301,  302,  349,  349,  353,  353,  359,  359,
      370,  370,  286,  357,  288,  356,  290,  355,  292,  352,
      294,  372,  372,  351,  302,  349,  349,  350,  348,  354,

      347,  360,  346,  371,  374,  374,  376,  376,  353,  353,
      378,  378,  381,  381,  373,  359,  359,  345,  350,  384,
      384,  370,  370,  372,  372,  374,  374,  375,  344,  377,
      343,  354,  342,  379,  341,  382,  376,  376,  360,  378,
      378,  205,  385,  340,  371,  339,  373,  205,  375,  392,
      392,  381,  381,  394,  394,  384,  384,  392,  392,  377,
      394,  394,  379,  401,  401,  401,  401,  338,  205,  205,
      337,  336,  393,  335,  382,  334,  395,  333,  385,  332,
      393,  331,  330,  395,  329,  328,  402,  327,  402,   50,
      326,   50,  144,  144,  144,  325,  324,  323,  322,  205,

      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  297,
      296,  295,  284,  283,  282,  281,  280,  231,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  205,  231,  265,  261,  260,  259,  256,  253,
      252,  240,  239,  231,  238,  237,  236,  235,  234,  233,
      232,  231,  205,  230,  229,  228,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  145,  145,
      203,  202,  201,  200,  199,  198,  187,  186,  183,  182,

      181,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  148,
      147,  145,  137,  136,  135,  134,  118,  117,  116,  115,
      114,  113,  112,   97,   96,   95,   92,   89,   78,   77,
       75,   74,   73,   51,   49,  411,    3,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411
    } ;

static const flex_int16_t yy_chk[736] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        6,    6,   10,   10,   17,   26,   48,   48,   18,   17,
       18,   18,   18,   18,   18,   18,   18,   18,   19,   29,

       19,   19,   19,   19,   19,   19,   19,   19,   27,   28,
       29,   28,   32,   39,   79,   34,   27,   40,   26,   79,
       32,   38,   41,  110,   40,  413,   40,   52,   52,   41,
      409,  110,   10,   10,   34,   67,   38,  170,   39,   28,
      408,   27,   38,   56,   56,  407,   38,   41,  406,   40,
       59,   59,   10,   10,   14,   14,   60,   60,   65,   65,
      198,   41,  404,  170,   66,   66,   56,   58,   58,  403,
       67,  116,  116,   59,  198,  198,  400,   52,   52,   60,
      399,   65,   58,   58,   58,   58,   58,   66,  119,  119,
       58,  121,  121,  397,  116,   67,  396,   52,   52,  122,

      122,  203,  203,  200,   14,   14,   14,   14,  207,  207,
      391,  119,  389,   14,  121,  388,   14,  200,  200,   58,
      386,  369,  122,  143,   14,   14,   14,   14,   69,   69,
       69,   69,   69,   69,   69,   69,   58,   70,  367,   70,
       70,   70,   70,   70,   70,   70,   70,   71,  366,   71,
       71,   71,   71,   71,   71,   71,   71,   72,  143,   72,
       72,   72,   72,   72,   72,   72,   72,  123,  123,  124,
      124,  125,  125,  126,  126,  130,  130,  132,  132,  138,
      138,  140,  140,  143,  199,  199,  199,  199,  199,  365,
      123,  364,  124,  362,  125,  358,  126,  356,  130,  346,

      132,  344,  138,  343,  140,  146,  146,  146,  146,  146,
      146,  146,  146,  184,  184,  188,  188,  190,  190,  192,
      192,  194,  194,  196,  196,  212,  244,  244,  212,  245,
      245,  246,  246,  247,  247,  342,  184,  212,  188,  341,
      190,  340,  192,  252,  194,  339,  196,  248,  248,  244,
      253,  253,  245,  338,  246,  337,  247,  252,  252,  285,
      285,  287,  287,  289,  289,  291,  291,  293,  293,  335,
      248,  301,  301,  253,  328,  328,  331,  331,  336,  336,
      347,  347,  285,  334,  287,  333,  289,  332,  291,  330,
      293,  348,  348,  329,  301,  349,  349,  328,  327,  331,

      326,  336,  325,  347,  351,  351,  352,  352,  353,  353,
      355,  355,  357,  357,  348,  359,  359,  324,  349,  361,
      361,  370,  370,  372,  372,  374,  374,  351,  323,  352,
      322,  353,  320,  355,  316,  357,  376,  376,  359,  378,
      378,  314,  361,  313,  370,  312,  372,  308,  374,  380,
      380,  381,  381,  383,  383,  384,  384,  392,  392,  376,
      394,  394,  378,  398,  398,  401,  401,  307,  306,  305,
      304,  303,  380,  300,  381,  299,  383,  298,  384,  297,
      392,  296,  295,  394,  284,  283,  398,  282,  401,  412,
      281,  412,  414,  414,  414,  280,  278,  277,  275,  274,

      273,  272,  271,  270,  269,  268,  267,  266,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  251,
      250,  249,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  229,  228,  227,  226,  224,  223,  222,  221,
      220,  217,  215,  214,  213,  211,  210,  209,  204,  202,
      201,  187,  186,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  169,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  144,  142,
      137,  136,  135,  134,  129,  128,  118,  117,  113,  112,

      111,  109,  108,  107,  106,  105,  104,  103,  102,  101,
      100,   99,   98,   97,   96,   95,   94,   93,   92,   91,
       89,   88,   87,   86,   85,   84,   83,   82,   80,   78,
       77,   68,   64,   63,   62,   61,   55,   54,   53,   50,
       46,   44,   43,   37,   36,   35,   33,   30,   25,   24,
       23,   22,   21,    9,    7,    3,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[100] =
    {   0,
1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexicon.l"
/*Function:词法分析模块，对每个终结符建立一个叶子结点，返回记号，供bison语法分析使用*/
#line 3 "lexicon.l"
#include "io.h"
#include "stdio.h"
#include "stdlib.h"
#include "syntax.h"
#include "semantics.h"
#line 782 "lexicon.cpp"
#line 783 "lexicon.cpp"

#define INITIAL 0

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 109 "lexicon.l"

#line 994 "lexicon.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 412 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 657 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 110 "lexicon.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 111 "lexicon.l"
{ yylval.a = newAst("str", 0, yylineno); return str; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 112 "lexicon.l"
{ yylval.a = newAst("bl", 0, yylineno); return bl; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 113 "lexicon.l"
{ yylval.a = newAst("TYPE", 0, yylineno); return TYPE; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 114 "lexicon.l"
{ yylval.a = newAst("a1", 0, yylineno); return a1; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 115 "lexicon.l"
{ yylval.a = newAst("a2", 0, yylineno); return a2; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 116 "lexicon.l"
{ yylval.a = newAst("a3", 0, yylineno); return a3; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 117 "lexicon.l"
{ yylval.a = newAst("a4", 0, yylineno); return a4; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 118 "lexicon.l"
{ yylval.a = newAst("a5", 0, yylineno); return a5; }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 119 "lexicon.l"
{ yylval.a = newAst("a6", 0, yylineno); return a6; }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 120 "lexicon.l"
{ yylval.a = newAst("aux1", 0, yylineno); return aux1; }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 121 "lexicon.l"
{ yylval.a = newAst("aux2", 0, yylineno); return aux2; }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 122 "lexicon.l"
{ yylval.a = newAst("aux3", 0, yylineno); return aux3; }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 123 "lexicon.l"
{ yylval.a = newAst("aux4", 0, yylineno); return aux4; }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 124 "lexicon.l"
{ yylval.a = newAst("aux5", 0, yylineno); return aux5; }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 125 "lexicon.l"
{ yylval.a = newAst("x", 0, yylineno); return x; }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 126 "lexicon.l"
{ yylval.a = newAst("y", 0, yylineno); return y; }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 127 "lexicon.l"
{ yylval.a = newAst("z", 0, yylineno); return z; }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 128 "lexicon.l"
{ yylval.a = newAst("a", 0, yylineno); return a; }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 129 "lexicon.l"
{ yylval.a = newAst("b", 0, yylineno); return b; }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 130 "lexicon.l"
{ yylval.a = newAst("c", 0, yylineno); return c; }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 131 "lexicon.l"
{ yylval.a = newAst("mode", 0, yylineno); return mode; }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 132 "lexicon.l"
{ yylval.a = newAst("baseRefSys", 0, yylineno); return baseRefSys; }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 133 "lexicon.l"
{ yylval.a = newAst("velAxis", 0, yylineno); return velAxis; }
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 134 "lexicon.l"
{ yylval.a = newAst("accAxis", 0, yylineno); return accAxis; }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 135 "lexicon.l"
{ yylval.a = newAst("decAxis", 0, yylineno); return decAxis; }
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 136 "lexicon.l"
{ yylval.a = newAst("jerkAxis", 0, yylineno); return jerkAxis; }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 137 "lexicon.l"
{ yylval.a = newAst("velPath", 0, yylineno); return velPath; }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 138 "lexicon.l"
{ yylval.a = newAst("accPath", 0, yylineno); return accPath; }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 139 "lexicon.l"
{ yylval.a = newAst("decPath", 0, yylineno); return decPath; }
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 140 "lexicon.l"
{ yylval.a = newAst("jerkPath", 0, yylineno); return jerkPath; }
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 141 "lexicon.l"
{ yylval.a = newAst("velOri", 0, yylineno); return velOri; }
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 142 "lexicon.l"
{ yylval.a = newAst("accOri", 0, yylineno); return accOri; }
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 143 "lexicon.l"
{ yylval.a = newAst("decOri", 0, yylineno); return decOri; }
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 144 "lexicon.l"
{ yylval.a = newAst("jerkOri", 0, yylineno); return jerkOri; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 145 "lexicon.l"
{ yylval.a = newAst("World", 0, yylineno); return World; }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 146 "lexicon.l"
{}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 147 "lexicon.l"
{ yylval.a = newAst("PTP", 0, yylineno); return PTP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 148 "lexicon.l"
{ yylval.a = newAst("LIN", 0, yylineno); return Lin; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 149 "lexicon.l"
{ yylval.a = newAst("CIRC", 0, yylineno); return Circ; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 150 "lexicon.l"
{ yylval.a = newAst("PTPRel", 0, yylineno); return PTPRel; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 151 "lexicon.l"
{ yylval.a = newAst("LinRel", 0, yylineno); return LinRel; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 152 "lexicon.l"
{ yylval.a = newAst("StopRobot", 0, yylineno); return StopRobot; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 153 "lexicon.l"
{ yylval.a = newAst("RefRobotAxis", 0, yylineno); return RefRobotAxis; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 154 "lexicon.l"
{ yylval.a = newAst("RefRobotAxisAsync", 0, yylineno); return RefRobotAxisAsync; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 155 "lexicon.l"
{ yylval.a = newAst("MoveRobotAxis", 0, yylineno); return MoveRobotAxis; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 156 "lexicon.l"
{ yylval.a = newAst("Dyn", 0, yylineno); return Dyn; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 157 "lexicon.l"
{ yylval.a = newAst("Dynovr", 0, yylineno); return Dynovr; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 158 "lexicon.l"
{ yylval.a = newAst("Ramp", 0, yylineno); return Ramp; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 159 "lexicon.l"
{ yylval.a = newAst("Refsys", 0, yylineno); return Refsys; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 160 "lexicon.l"
{ yylval.a = newAst("Tool", 0, yylineno); return Tool; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 161 "lexicon.l"
{ yylval.a = newAst("WaitTime", 0, yylineno); return WaitTime; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 162 "lexicon.l"
{ yylval.a = newAst("Stop", 0, yylineno); return Stop; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 163 "lexicon.l"
{ yylval.a = newAst("Notice", 0, yylineno); return Notice; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 164 "lexicon.l"
{ yylval.a = newAst("Warning", 0, yylineno); return Warning; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 165 "lexicon.l"
{ yylval.a = newAst("Error", 0, yylineno); return Error; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 166 "lexicon.l"
{ yylval.a = newAst("CALL", 0, yylineno); return CALL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 167 "lexicon.l"
{ yylval.a = newAst("WAIT", 0, yylineno); return WAIT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 168 "lexicon.l"
{ yylval.a = newAst("IF", 0, yylineno); return IF; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 169 "lexicon.l"
{ yylval.a = newAst("THEN", 0, yylineno); return THEN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 170 "lexicon.l"
{ yylval.a = newAst("ELSE", 0, yylineno); return ELSE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 171 "lexicon.l"
{ yylval.a = newAst("ELSEIF", 0, yylineno); return ELSEIF; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 172 "lexicon.l"
{ yylval.a = newAst("END_IF", 0, yylineno); return END_IF; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 173 "lexicon.l"
{ yylval.a = newAst("WHILE", 0, yylineno); return WHILE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 174 "lexicon.l"
{ yylval.a = newAst("DO", 0, yylineno); return DO; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 175 "lexicon.l"
{ yylval.a = newAst("END_WHILE", 0, yylineno); return END_WHILE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 176 "lexicon.l"
{ yylval.a = newAst("LOOP", 0, yylineno); return LOOP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 177 "lexicon.l"
{ yylval.a = newAst("END_LOOP", 0, yylineno); return END_LOOP; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 178 "lexicon.l"
{ yylval.a = newAst("RUN", 0, yylineno); return RUN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 179 "lexicon.l"
{ yylval.a = newAst("KILL", 0, yylineno); return KILL; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 180 "lexicon.l"
{ yylval.a = newAst("RETURN", 0, yylineno); return RETURN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 181 "lexicon.l"
{ yylval.a = newAst("GOTO", 0, yylineno); return GOTO; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 182 "lexicon.l"
{ yylval.a = newAst("intgr", 0, yylineno); return intgr; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 183 "lexicon.l"
{ yylval.a = newAst("flt", 0, yylineno); return flt; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 184 "lexicon.l"
{ yylval.a = newAst("id", 0, yylineno); return id; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 185 "lexicon.l"
{ yylval.a = newAst("ASSIGN", 0, yylineno); return ASSIGN; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 186 "lexicon.l"
{ yylval.a = newAst("MINUS", 0, yylineno); return MINUS; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 187 "lexicon.l"
{ yylval.a = newAst("LP", 0, yylineno); return LP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 188 "lexicon.l"
{ yylval.a = newAst("RP", 0, yylineno); return RP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 189 "lexicon.l"
{ yylval.a = newAst("LC", 0, yylineno); return LC; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 190 "lexicon.l"
{ yylval.a = newAst("RC", 0, yylineno); return RC; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 191 "lexicon.l"
{ yylval.a = newAst("COMMA", 0, yylineno); return COMMA; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 192 "lexicon.l"
{ yylval.a = newAst("COLON", 0, yylineno); return COLON; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 193 "lexicon.l"
{ yylval.a = newAst("AND", 0, yylineno); return AND; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 194 "lexicon.l"
{ yylval.a = newAst("OR", 0, yylineno); return OR; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 195 "lexicon.l"
{ yylval.a = newAst("XOR", 0, yylineno); return XOR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 196 "lexicon.l"
{ yylval.a = newAst("MUL", 0, yylineno); return MUL; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 197 "lexicon.l"
{ yylval.a = newAst("DIV", 0, yylineno); return DIV; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 198 "lexicon.l"
{ yylval.a = newAst("PLUS", 0, yylineno); return PLUS; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 199 "lexicon.l"
{ yylval.a = newAst("EQ", 0, yylineno); return EQ; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 200 "lexicon.l"
{ yylval.a = newAst("NE", 0, yylineno); return NE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 201 "lexicon.l"
{ yylval.a = newAst("LE", 0, yylineno); return LE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 202 "lexicon.l"
{ yylval.a = newAst("LT", 0, yylineno); return LT; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 203 "lexicon.l"
{ yylval.a = newAst("GE", 0, yylineno); return GE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 204 "lexicon.l"
{ yylval.a = newAst("GT", 0, yylineno); return GT; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 205 "lexicon.l"
{ yylval.a = newAst("NOT", 0, yylineno); return NOT; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 206 "lexicon.l"
{ yylval.a = newAst("DOT", 0, yylineno); return DOT; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 207 "lexicon.l"
{ printf("Error type at line %d: Mystirious charachter '%s'\n", yylineno, yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 208 "lexicon.l"
ECHO;
	YY_BREAK
#line 1590 "lexicon.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 412 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 412 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 411);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (_isatty( _fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 208 "lexicon.l"

